meta:
  id: "cc_byobu"
  name: "Byobu"
  title: "Enable/Disable byobu system wide or for default user"
  description: |
    This module controls whether byobu is enabled or disabled system wide and for
    the default system user. If byobu is to be enabled, this module will ensure it
    is installed. Likewise, if it is to be disabled, it will be removed if
    installed.

    Valid configuration options for this module are:

      - ``enable-system``: enable byobu system wide
      - ``enable-user``: enable byobu for the default user
      - ``disable-system``: disable byobu system wide
      - ``disable-user``: disable byobu for the default user
      - ``enable``: enable byobu both system wide and for default user
      - ``disable``: disable byobu for all users
      - ``user``: alias for ``enable-user``
      - ``system``: alias for ``enable-system``
  distros: ["ubuntu", "debian"]
  frequency: "once-per-instance"
  examples:
    - byobu_by_default: "enable-user"
    - byobu_by_default: "disable-system"
schema:
  type: "object"
  properties:
    byobu_by_default:
      type: "string"
      enum:
        - "enable-system"
        - "enable-user"
        - "disable-system"
        - "disable-user"
        - "enable"
        - "disable"
        - "user"
        - "system"
